# Generated by Django 5.0.4 on 2024-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_prefabitem_internalname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefabitem",
            name="internalname",
            field=models.CharField(default="unset", max_length=100, unique=True),
        ),
    ]
