# Generated by Django 5.0.4 on 2024-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefabitem",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
