# Generated by Django 5.0.4 on 2024-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_prefabitem_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefabitem",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="prefabitems/"),
        ),
    ]
