# Generated by Django 5.0.4 on 2024-06-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_prefabitem_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefabitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
