# Generated by Django 5.0.4 on 2024-07-03 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.AddField(
            model_name="order",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="date_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
