# Generated by Django 5.0.4 on 2024-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_order_date_order_date_added_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
