# Generated by Django 5.0.4 on 2024-07-07 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_client_bank_client_cui_client_iban_client_reg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_due",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
