# Generated by Django 5.0.4 on 2024-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_order_date_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
