# Generated by Django 5.0.4 on 2024-09-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_order_discount_order_shipping_order_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefabitem",
            name="thumbnail",
            field=models.TextField(default="https://via.placeholder.com/250"),
        ),
    ]
