# Generated by Django 5.0.4 on 2025-01-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_prefabitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefabitem',
            name='dimensions',
            field=models.TextField(blank=True),
        ),
    ]
