# Generated by Django 5.0.4 on 2025-01-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_prefabitem_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefabStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=8)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('prefab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prefabitem')),
            ],
        ),
    ]
