# Generated by Django 5.0.4 on 2025-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_prefabstockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefabitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_due',
            field=models.DateTimeField(),
        ),
    ]
